flameshot_example.sh

Adds a upload script for Flameshot, since ShareX is not supported on GNU/Linux.

Flameshot Uploader script

---

.npmrc
README.md
ass.js
package-lock.json
package.json
thumbnails.js
utils.js

Just read the commit notes, I'm tired

Package stuff

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

- Operating System: N/A
- Node version: N/A
- NPM version: N/A

improved PR template & added Contributing Guidelines

---

metrics.js

- Operating System: I am
- Node version: the lead
- NPM version: developer

Fix metrics printing too much

---

.github/ISSUE_TEMPLATE/report-bug.yml

- Operating System: n/a
- Node version: n/a
- NPM version: n/a
Fixes Bug Report form because apparently GitHub form placeholders have a secret undocumented max length.

fixed Bug form, probably

---

.github/ISSUE_TEMPLATE/report-bug.yml

- Operating System:
- Node version:
- NPM version:

Fixed Bug report template for good. Maybe.

---

routers/resource.js

- Node version: 14
- NPM version: 7
Fixes duplicate author bug, as described in #45.

Fix duplicate author (closes #45)

---

README.md
package.json

README needed some improvements

Freshened up the README

---

package.json

- Operating System:
- Node version:
- NPM version:

Woops forgot version bump for 0.8.3

---

README.md
routers/resource.js
setup.js
views/view.pug

- Node version: 14
- NPM version: 7
Added `viewDirect`, which changes the viewing mode for browsers between direct and the default view page.

Added setting to view direct resource in browser

---

package-lock.json
package.json

- Node version: 14
- NPM version: 7
Updated dependencies & version bump for release 0.8.6

Updated packages & version 0.8.6

---

README.md
ass.js
data.js
package-lock.json
package.json

- Node version: 7
- NPM version: 14
Switches from ass-storage-engine `0.2.7` to Papito `0.3.1`. It's the same package, but new name because I have other plans for it.

Switch to Papito (replaces ass-storage-engine)

---

compose.yaml

- Operating System: Linux arch 5.14.5-arch1-1 x86_64 GNU/Linux
- Node version: 14.17.6
- NPM version: 7.24.0
using `color` just from the context of `FORCE_`**COLOR**

replace `colour` with `color` :nobritish:

---

Dockerfile

- Operating System: Linux arch 5.14.5-arch1-1 x86_64 GNU/Linux
- Node version: 14.17.6
- NPM version: 7.24.0
Please see https://stackoverflow.com/questions/39223249/multiple-run-vs-single-chained-run-in-dockerfile-which-is-better

collapse `RUN` declaration in Dockerfile.

---

routers/upload.js

Fixes duplicate ID's failing to upload. If an ID already exists, it tries again until a unique ID is found.
~~Currently will infinitely hang if all available ID's are exhausted.~~ Fixed in [`3cb2ca1`](https://github.com/tycrek/ass/pull/77/commits/3cb2ca135d9724e85c4ba2451bcb951eadc25eb7)
This PR will close Issue #75.

Added check for duplicate ID's (closes #75)

---

README.md
package-lock.json
package.json

This update brings in a few major changes, such as using Papito instead of ass-storage-engines now (same codebase but modified for more general purpose use).
If you use webhooks, you'll need to fix your headers (check the README for info).
- Added options to replace or remove spaces in filenames
- Added dynamic data engines with new config entry
- Added `X-Ass-Webhook-Url` header and removed webhook token/client headers
- Added check for duplicate ID's
- Improved Docker assets (`compose.yml` & `Dockerfile`) thanks to @d1snin
- Switched to `discord-webhook-node`, dropping `discord.js` for webhooks
- Switched to using Papito data engines (previously known as ass StorageEngines)
Hosts will need to run `npm run setup` …

Version 0.8.7

---

routers/upload.js

Fixed webhooks because I forgot to change one line, oops.

Fixed webhooks oops

---

.github/autoapproval.yml

GitHub branch protection blocks me from approving my own PR's.

Added `.github/autoapproval.yml` for auto-approve bot

---

ass.js

Checks if the provided custom index is loaded as a `Function` to improve reliability & troubleshooting.

Only load custom index if exported function is detected

---

ass.js

- Fixed custom index loading trying to load as Boolean
- Fixed incorrect path for loading README as index

Fixed custom index loading trying to load as Boolean

---

src/thumbnails.ts
src/vibrant.ts

- Operating System: Bindows Ben
- Node version: Bourteen
- npm version: Beight
Fixes Webp files failing to upload because Jimp doesn't support webp oliver-moran/jimp#144.

Added shitty patch for `webp` failing to upload

---

src/routers/resource.ts

- Operating System: Binbows Ben
- Node version: Bourteen
- npm version: Beight
Fixes a problem described in #103. As the main concern in that is that ass crashes and could cause downtime for users, this PR will close that Issue.

Fix crash if file is missing from`uploads/` (closes #103)

---

.github/README.md
.github/workflows/ts-build.yml
Dockerfile
package-lock.json
package.json
tsconfig.json

- Node version: Node 16.14.0
- npm version: NPM 8.3.1
Previously, running ass on Node 16 was blocked due to some dependencies not working on Node 16. Luckily ass no longer uses those, and testing Node 16 was a success. This PR will close #118.

Properly support Node 16

---

.github/README.md
package-lock.json
package.json
src/ass.ts
src/setup.js

- Node version: 16.14
- npm version: 8
Custom indexes are now easier to plug into ass. No more config modifications, now you can simply have a file in the `share/` directory named either `index.html` or `index.js` (for custom Express middleware) and ass will automatically serve your content.
Additionally in this release:
- New theme system (more to come in a later version with bigger announcement)
- Updated Docker files: use `node` user rather than `root`; removed redundant directives; simplified command order

Rewrote logic for custom index plugging (more seamless now)

---

package-lock.json
package.json
src/nightmare.ts
src/storage.ts
src/types/gps-metadata-remover.d.ts

Supported filetypes are: JPG, PNG, TIF, MOV, MP4. Using [@xoi/gps-metadata-remover](https://www.npmjs.com/package/@xoi/gps-metadata-remover).
Closes #91
- Node version: 16.14.0
- npm version: 8.17.0

Strip EXIF GPS data from files during upload

---

src/routers/upload.ts
src/setup.js
src/types/json.d.ts

- Node version: 16.14
- npm version: 8.17
Adds options to log all uploads from all users with a webhook.
This will close #142

feat: added global admin webhook (#142)

---

src/ass.ts
src/routers/api.ts

- Node version: 16.14.0
- npm version: 8.17.0
Developer API. For more info see #179 for now.
Will close #179 when merged.

Developer API

---

package-lock.json
package.json
src/routers/upload.ts

- Node version: 16
- npm version: 8
Switches to https://github.com/tycrek/discord-hookr as it is more up to date than the library it's forked from.

v0.14.0/hookr

---

.github/README.md
src/routers/upload.ts
src/types/json.d.ts

- Node version: 16
- npm version: 8
Closes #173 

added server-side embed configuration (#173)

---

src/thumbnails.ts

Thumbnail from center of images instead of stretching it

Center Thumbnails

---

.github/workflows/automation.yml

This PR add a GH workflow for to label and PR when merge conflict is detected.

Added GH workflow for merge conflicts

---

backend/UserConfig.ts
backend/ratelimit.ts
backend/routers/api.ts
backend/routers/index.ts
common/types.d.ts
frontend/setup.mts
package-lock.json
package.json
views/setup.pug

- Operating System: artix linux w/linux 6.5.5
- Node version: 20.8.0
- npm version: 10.1.0
adds customizable rate limiting to ass using a `ratelimit` section in the config.
[Contributing Guidelines]: https://github.com/tycrek/ass/blob/master/.github/CONTRIBUTING.md

configurable rate limiting

---

backend/ratelimit.ts
backend/routers/api.ts
backend/routers/index.ts

- Operating System: see prev
- Node version: see prev
- npm version: see prev
please mergeg ok ijg now
[Contributing Guidelines]: https://github.com/tycrek/ass/blob/master/.github/CONTRIBUTING.md

fix broken middleware on setup
